<?xml version="1.0"?>
<package format="3">
  <name>agv_obstacle_guard</name>
  <version>0.0.1</version>

  <description>
    AGV lidar obstacle guard, recovery watchdog,
    and controlled mission safety hold.
  </description>

  <maintainer email="seniru@localhost">seniru</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
